version: '3.8'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./config.json:/app/config.json:ro  # Mount the config file as read-only
    environment:
      - FLASK_ENV=development
    stdin_open: true
    tty: true
